stages:
    - build jar
    - build image
    - push image

build:
  stage: build jar
  tags:
    - maven
  script:
    - mvn package -DskipTests
  artifacts:
    paths:
      - target/*.jar
    expire_in: 1 week
  only:
    - develop

docker:
  stage: build image
  services:
    - docker:19.03.12-dind
  tags:
    - docker-builder
  before_script:
    - update-ca-certificates
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  script:
    - docker pull $CI_REGISTRY_IMAGE:latest || true
    - docker build --cache-from $CI_REGISTRY_IMAGE:latest --tag $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA --tag $CI_REGISTRY_IMAGE:latest .
    - docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA
    - docker push $CI_REGISTRY_IMAGE:latest
  only:
    - develop

deploy:
  stage: push image
  tags:
    - ssh
  before_script:
    - eval $(ssh-agent -s)
    - ssh-add - <<< "${SSH_PRIVATE_KEY}"
    - 'mkdir -p ~/.ssh && ssh-keyscan -H "$SSH_KNOWN_HOST" >> ~/.ssh/known_hosts'
  script:
    - export
    - ssh "$SSH_LOGIN"@"$SSH_KNOWN_HOST" "cd $LOCATION; docker-compose down; docker-compose pull; docker-compose up -d; exit"
  only:
    - develop


