stages:
    - build jar
    - deploy

build:
  stage: build jar
  before_script:
    - source .${CI_COMMIT_REF_NAME}.env
  script:
    - mvn clean install -DskipTests=true
  artifacts:
    paths:
      - target/*.jar
    expire_in: 1 week
  only:
    - master

deploy:
  stage: deploy
  before_script:
    - which ssh-agent
    - eval $(ssh-agent -s)
    - ssh-add - <<< "${SSH_PRIVATE_KEY}"
    - '[[ -f /.dockerenv ]] && mkdir -p ~/.ssh && ssh-keyscan -H "$SSH_KNOWN_HOST" >> ~/.ssh/known_hosts'
    - cat ~/.ssh/known_hosts
    - mvn clean install -DskipTests=true
    - pwd
  only:
    - develop

